In [2]:
import numpy as np
import pandas as pd

import numpy as np

# Task 1: Create a 5x5 matrix with random integers from 1 to 50
matrix = np.random.randint(1, 51, size=(5, 5))
print("Original Matrix:")
print(matrix)

# Task 2: Find numbers greater than 25
print("\nNumbers greater than 25:")
print(matrix[matrix > 25])

# Task 3: Replace even numbers with 0 without changing the original
modified_matrix = matrix.copy()
modified_matrix[modified_matrix % 2 == 0] = 0

print("\nModified Matrix:")
print(modified_matrix)

print("\nOriginal Matrix remains unchanged:")
print(matrix)

Original Matrix:
[[39 33  3 12  3]
 [34 37 24  4 18]
 [ 8 29  4 32  5]
 [ 9 20 24 48 29]
 [ 6 49 12 10 49]]

Numbers greater than 25:
[39 33 34 37 29 32 48 29 49 49]

Modified Matrix:
[[39 33  3  0  3]
 [ 0 37  0  0  0]
 [ 0 29  0  0  5]
 [ 9  0  0  0 29]
 [ 0 49  0  0 49]]

Original Matrix remains unchanged:
[[39 33  3 12  3]
 [34 37 24  4 18]
 [ 8 29  4 32  5]
 [ 9 20 24 48 29]
 [ 6 49 12 10 49]]


In [4]:
# task-4
arr = np.random.randint(1, 101, size=10)

normalized = (arr - arr.min()) / (arr.max() - arr.min())

print("Original Array:", arr)
print("Normalized Array:", normalized)
normalized = np.clip(normalized, 1e-10, 1 - 1e-10)

""""Min-max normalization uses this formula:

x
norm
	​

=
max(x)−min(x)
x−min(x)
	​


This scales the minimum to 0 and the maximum to 1, with other values between them. Therefore, the endpoints are included, so the values are not strictly between 0 and 1.

If the task literally requires every value to be strictly between 0 and 1, you can clip the normalized values slightly:"""

Original Array: [65 43 45 46 41 68  8 47 32 37]
Normalized Array: [0.95       0.58333333 0.61666667 0.63333333 0.55       1.
 0.         0.65       0.4        0.48333333]


In [5]:
# question2
#Task 1: Create a DataFrame with missing salary values
import pandas as pd
import numpy as np

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Ravi", "Priya", "Amit", "Sneha", "Kiran", "Divya"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance"],
    "Age": [25, 30, 28, 35, 27, 32],
    "Salary": [50000, np.nan, 60000, 70000, np.nan, 80000]
}

df = pd.DataFrame(data)
print(df)

   Employee_ID   Name Department  Age   Salary
0          101   Ravi         IT   25  50000.0
1          102  Priya         HR   30      NaN
2          103   Amit         IT   28  60000.0
3          104  Sneha    Finance   35  70000.0
4          105  Kiran         HR   27      NaN
5          106  Divya    Finance   32  80000.0


In [6]:
# task-2 Count missing values in each column
print(df.isnull().sum())

Employee_ID    0
Name           0
Department     0
Age            0
Salary         2
dtype: int64


In [7]:
# task-3 Fill missing salaries with the median salary of each department
df["Salary"] = df["Salary"].fillna(
    df.groupby("Department")["Salary"]
      .transform("median")
)

print(df)

   Employee_ID   Name Department  Age   Salary
0          101   Ravi         IT   25  50000.0
1          102  Priya         HR   30      NaN
2          103   Amit         IT   28  60000.0
3          104  Sneha    Finance   35  70000.0
4          105  Kiran         HR   27      NaN
5          106  Divya    Finance   32  80000.0


In [8]:
#Task-4: Calculate annual bonus and average salary per department
df["Annual_Bonus"] = df["Salary"] * 0.10

average_salary = df.groupby("Department")["Salary"].mean()

print("DataFrame with Annual Bonus:")
print(df)

print("\nAverage Salary by Department:")
print(average_salary)

DataFrame with Annual Bonus:
   Employee_ID   Name Department  Age   Salary  Annual_Bonus
0          101   Ravi         IT   25  50000.0        5000.0
1          102  Priya         HR   30      NaN           NaN
2          103   Amit         IT   28  60000.0        6000.0
3          104  Sneha    Finance   35  70000.0        7000.0
4          105  Kiran         HR   27      NaN           NaN
5          106  Divya    Finance   32  80000.0        8000.0

Average Salary by Department:
Department
Finance    75000.0
HR             NaN
IT         55000.0
Name: Salary, dtype: float64


In [9]:
#Q3. NumPy Array Reshaping & Slicing Challenge
#Task 1–2: Create a 1D array and reshape it into a 4×5 matrix
import numpy as np

arr = np.arange(1, 21)

matrix = arr.reshape(4, 5)

print("1D Array:")
print(arr)

print("\n4x5 Matrix:")
print(matrix)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

4x5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [10]:
# Task 3: Extract the second and third columns
print(matrix[:, 1:3])

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]


In [11]:
#task 4: Extract the four corner elements
corners = matrix[[0, 0, -1, -1], [0, -1, 0, -1]]

print(corners)

[ 1  5 16 20]


In [12]:
#Q4. Pandas Filtering & Conditional Selection
#Task 1: Create a DataFrame
import pandas as pd

data = {
    "Product": ["Laptop", "Mouse", "Monitor", "Keyboard", "Printer", "Tablet"],
    "Category": ["Electronics", "Accessories", "Electronics",
                 "Accessories", "Electronics", "Electronics"],
    "Price": [60000, 400, 12000, 800, 15000, 25000],
    "Stock": [15, 100, 30, 10, 45, 60]
}

df = pd.DataFrame(data)

print(df)

    Product     Category  Price  Stock
0    Laptop  Electronics  60000     15
1     Mouse  Accessories    400    100
2   Monitor  Electronics  12000     30
3  Keyboard  Accessories    800     10
4   Printer  Electronics  15000     45
5    Tablet  Electronics  25000     60


In [13]:
# Task 2: Filter products where Price > 500 and Stock < 50
filtered_df = df[(df["Price"] > 500) & (df["Stock"] < 50)]

print(filtered_df)

    Product     Category  Price  Stock
0    Laptop  Electronics  60000     15
2   Monitor  Electronics  12000     30
3  Keyboard  Accessories    800     10
4   Printer  Electronics  15000     45


In [14]:
#Task 3–4: Add Restock_Needed and sort by Price descending
df["Restock_Needed"] = df["Stock"] < 20

df = df.sort_values(by="Price", ascending=False)

print(df)

    Product     Category  Price  Stock  Restock_Needed
0    Laptop  Electronics  60000     15            True
5    Tablet  Electronics  25000     60           False
4   Printer  Electronics  15000     45           False
2   Monitor  Electronics  12000     30           False
3  Keyboard  Accessories    800     10            True
1     Mouse  Accessories    400    100           False


In [15]:
# Q5. Vectorized Temperature & Math Operations
#Task 1–2: Generate Celsius temperatures and convert to Fahrenheit
import numpy as np

# Generate 10 random temperatures between 15 and 40 Celsius
celsius = np.random.uniform(15.0, 40.0, size=10)

# Convert all temperatures to Fahrenheit
fahrenheit = (celsius * 9 / 5) + 32

print("Celsius:", celsius)
print("Fahrenheit:", fahrenheit)

Celsius: [17.79431322 26.66106807 21.74757521 32.51204245 35.78851777 28.38641809
 28.41269316 34.22822082 25.08349601 38.48171393]
Fahrenheit: [ 64.02976379  79.98992253  71.14563538  90.52167641  96.41933198
  83.09555256  83.14284769  93.61079748  77.15029281 101.26708508]


In [16]:
#Task 3: Calculate square roots of numbers from 1 to 10
arr = np.arange(1, 11)

sqrt_arr = np.sqrt(arr)

print(sqrt_arr)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [17]:
#Task 4: Find the index of the maximum Fahrenheit temperature
max_index = np.argmax(fahrenheit)

print("Index of maximum temperature:", max_index)
print("Maximum Fahrenheit temperature:", fahrenheit[max_index])

Index of maximum temperature: 9
Maximum Fahrenheit temperature: 101.26708507658934


In [18]:
# Q6. Debugging NumPy Boolean Masking
import numpy as np

arr = np.array([10, 25, 30, 45, 60, 15, 50])

filtered_arr = arr[(arr > 20) and (arr < 50)]

print(filtered_arr)

"""NumPy comparisons produce arrays of Boolean values.
Python's and expects single truth values, so it cannot combine these Boolean arrays element by element. This raises a ValueError."""

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [20]:
import numpy as np

arr = np.array([10, 25, 30, 45, 60, 15, 50])

filtered_arr = arr[(arr > 20) & (arr < 50)]

print(filtered_arr)

[25 30 45]


In [21]:
import pandas as pd

data = {
    "Employee": ["Ravi", "Priya", "Amit"],
    "Department": ["IT", "HR", "Finance"],
    "Salary": [50000, 60000, 55000]
}

df = pd.DataFrame(data)

df_dropped = df.drop("Salaries", axis=1)

print(df_dropped)

"""The DataFrame column is named "Salary", but the code tries to drop "Salaries".

Because "Salaries" was not present Pandas raises a KeyError."""

KeyError: "['Salaries'] not found in axis"

In [22]:
import pandas as pd

data = {
    "Employee": ["Ravi", "Priya", "Amit"],
    "Department": ["IT", "HR", "Finance"],
    "Salary": [50000, 60000, 55000]
}

df = pd.DataFrame(data)

df_dropped = df.drop("Salary", axis=1)

print(df_dropped)

  Employee Department
0     Ravi         IT
1    Priya         HR
2     Amit    Finance
